### ISSUE TITLE
"next meetup" is out of date

### ISSUE THREAD

**Issue by mraaroncruz** [study-jams/study-jams.github.io#5]
The next jam is in the past.

> Wednesday, December 11th at 18:30 (cooperation with Wikidata Wednesday)

Maybe you can make meetings a data type and use some kind of setup like this to keep everything up to date.
https://css-tricks.com/a-site-for-front-end-development-conferences-built-with-11ty-on-netlify/#article-header-id-4

**Comment by hola-soy-milk** [comment]
D'oh! Good call.

I've added the new dates for now, and will look into this solution.
