### ISSUE TITLE
Typo in Where and When section

### ISSUE THREAD

**Issue by mraaroncruz** [study-jams/study-jams.github.io#6]
It says "We meet every two Wednesdays at Wikimedia Austria’s office:"
The correct way to write this is "every other Wednesday"

I can still see a problem with this being that the reader has no idea which was the last "every other wednesday"

I read this part before the latter part that said the date and was confused.

Maybe putting "where" into one section and "when and how often" into another section would clarify things a bit.

**Comment by hola-soy-milk** [comment]
Thanks so much for your feedback! 

I hope it's clearer now, what do you think:
https://study-jams.github.io/
